# Generated by Django 4.2 on 2023-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Studdent",
            new_name="Student",
        ),
    ]
